-- Uncomment to update member PROCEDURES.
-- \i ProMemberList.sql
-- \i ProMemberTree.sql
-- \i ProMemberSelect.sql
-- \i ProMemberInsert.sql
-- \i ProMemberUpdate.sql
-- \i ProMemberDelete.sql
-- \i ProMemberMapSpouse.sql
-- \i ProMemberDashboard.sql
-- \i ProMemberTimeline.sql
-- \i ProMemberExistsInFamily.sql
-- \i ProMemberHasRoot.sql
-- \i ProMemberGetParentId.sql
-- \i ProMemberGetRelation.sql
